FROM python:3.8.3-slim
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
# install psycopg2 dependencies
RUN apt-get update && apt-get install python3-pip python3-dev libpq-dev postgresql postgresql-contrib -y
RUN apt-get install libffi-dev
RUN apt-get install wkhtmltopdf -y

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code