# Generated by Django 3.2.9 on 2022-02-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='vendor',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
